<?php

    return[
        [
            'nome_corso' => 'Corso di formazione per RSPP/ASPP',
            'posti_disponibili' => '5',
            'cap_sede_corso' => '85024',
            'città_di_svolgimento' => 'Lavello',
            'indirizzo_di_svolgimento' => 'Via Bologna 24',
            'provincia' => 'PZ',
            'direttore_corso' => 'Matera Grazia',
            'docenti_corso' => 'Matera Grazia',
            'inizio_di_svolgimento' => '2023-08-11',
            'fine_svolgimento' => '2023-08-15',
            'genere_corso' => 'D.Lgs. 81/08',
            'numero_autorizzazione' => 'CFAL/875632',
            'durata_corso' => '12',
        ],
        [
            'nome_corso' => 'Corso di formazione per RSPP/ASPP',
            'posti_disponibili' => '4',
            'cap_sede_corso' => '85024',
            'città_di_svolgimento' => 'Lavello',
            'indirizzo_di_svolgimento' => 'Via Bologna 24',
            'provincia' => 'PZ',
            'direttore_corso' => 'Matera Grazia',
            'docenti_corso' => 'Matera Grazia',
            'inizio_di_svolgimento'=> '2023-08-11',
            'fine_svolgimento' => '2023-08-15',
            'genere_corso' => 'D.Lgs. 81/08',
            'numero_autorizzazione' => 'CFAL/875632',
            'durata_corso' => '12',
        ],
        [
            'nome_corso' => 'Corso di formazione per RSPP/ASPP',
            'posti_disponibili' => '10',
            'cap_sede_corso' => '85024',
            'città_di_svolgimento' => 'Lavello',
            'indirizzo_di_svolgimento' => 'Via Bologna 24',
            'provincia' => 'PZ',
            'direttore_corso' => 'Matera Grazia',
            'docenti_corso' => 'Matera Grazia',
            'inizio_di_svolgimento'=> '2023-08-11',
            'fine_svolgimento' => '2023-08-15',
            'genere_corso' => 'D.Lgs. 81/08',
            'numero_autorizzazione' => 'CFAL/875632',
            'durata_corso' => '12',
        ],
        [
            'nome_corso' => 'Corso di formazione per RSPP/ASPP',
            'posti_disponibili' => '11',
            'cap_sede_corso' => '85024',
            'città_di_svolgimento' => 'Lavello',
            'indirizzo_di_svolgimento' => 'Via Bologna 24',
            'provincia' => 'PZ',
            'direttore_corso' => 'Matera Grazia',
            'docenti_corso' => 'Matera Grazia',
            'inizio_di_svolgimento'=> '2023-08-11',
            'fine_svolgimento' => '2023-08-15',
            'genere_corso' => 'D.Lgs. 81/08',
            'numero_autorizzazione' => 'CFAL/875632',
            'durata_corso' => '12',
        ]
    ];
        
    
